### Step 1 - Import Libraries

In [22]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score

### Step 2 - Load Data

In [2]:
df = pd.read_csv('./Churn_Modelling.csv')
X = df.iloc[:, 3:13].values
y = df.iloc[:, 13].values

In [3]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


### Step 3 - Encode Categorical Data

In [5]:
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [6]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


### Step 4 - Encoding 'Geography' Column with OneHotEncoder

In [9]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [10]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Step 5 - Split Data

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

### Step 6 - Feature Scaling

In [15]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Build ANN Model

### Step 1 - Initialize the ANN

In [16]:
ann = tf.keras.models.Sequential()

### Step 2 - Initialize First Input and Hidden Layer

In [17]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Step 3 - Add Second Hidden Layer

In [18]:
ann.add(tf.keras.layers.Dense(units=1, activation='relu'))

## Train the ANN Model

### Step 1 - Compiling the ANN Model

In [19]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

### Step 2 - Model Fitting

In [20]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 5.7334 - accuracy: 0.4436
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 5.0017 - accuracy: 0.4947
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 4.2478 - accuracy: 0.5397
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 3.5502 - accuracy: 0.6005
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 3.1834 - accuracy: 0.6384
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 2.8631 - accuracy: 0.6700
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 2.6715 - accuracy: 0.6923
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 2.4289 - accuracy: 0.7089
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 2.2178 - accuracy: 0.6870
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 2.0445 - accura

### Modelling new data and make predictions

In [21]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 64ms/step
[[False]]


### Predict the Data with testing

In [24]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)

print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Accuracy Score and Confusion Matrix

In [25]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

accuracy_score(y_test, y_pred)
print(accuracy_score(y_test, y_pred))

[[1518   77]
 [ 229  176]]
0.847
